[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "./railway-production.sh"

[environments.production]
EUREKA_PORT = "8761"
SPRING_PROFILES_ACTIVE = "production"
JAVA_OPTS = "-Xmx512m -Djava.security.egd=file:/dev/./urandom"

[environments.production.variables]
PORT = { default = "8080" }
EUREKA_PORT = { default = "8761" }
PRODUCTS_PORT = { default = "8081" }
SALES_PORT = { default = "8082" }
