[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
EUREKA_PORT = "8761"
SPRING_PROFILES_ACTIVE = "production"

[environments.production.variables]
PORT = { default = "8080" }
EUREKA_PORT = { default = "8761" }
PRODUCTS_PORT = { default = "8081" }
SALES_PORT = { default = "8082" }
