version: '3.8'

services:
  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    container_name: abc-motor-eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
    networks:
      - abc-motor-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: abc-motor-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=gateway
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - abc-motor-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  msvc-products:
    build:
      context: ../msvc-products
      dockerfile: Dockerfile
    container_name: abc-motor-products
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-products
      - MONGODB_URI=${MONGODB_URI:-mongodb+srv://jjgarcia6:PTkW8S8M6b6jgMuc@cluster0.u3mhx.mongodb.net/products_db?retryWrites=true&w=majority&appName=Cluster0}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-jjgarcia6}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-PTkW8S8M6b6jgMuc}
      - MONGODB_CLUSTER=${MONGODB_CLUSTER:-cluster0.u3mhx.mongodb.net}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-products_db}
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - abc-motor-network
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  msvc-sales:
    build:
      context: ../msvc-sales
      dockerfile: Dockerfile
    container_name: abc-motor-sales
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=msvc-sales
    depends_on:
      eureka-server:
        condition: service_healthy
      msvc-products:
        condition: service_healthy
    networks:
      - abc-motor-network
    deploy:
      replicas: 2
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

networks:
  abc-motor-network:
    driver: bridge
    name: abc-motor-network

volumes:
  eureka-data:
    name: abc-motor-eureka-data
